import Link from 'next/link';
import {notFound} from 'next/navigation';
import {MessageCircle,MapPin} from 'lucide-react';
import {getProperty} from '@/lib/airtable';
import {site,whatsappLink} from '@/config/site';
import {priceLabel} from '@/components/property-card';
import {Gallery} from '@/components/gallery';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const p=await getProperty((await params).id);return {title:p?.title||'Property not found',description:p?.description.slice(0,160)};}
export default async function PropertyDetail({params}:{params:Promise<{id:string}>}){const p=await getProperty((await params).id);if(!p)notFound();const status=p.status==='Rented'?'Recently Rented':p.status;return <div className="shell"><div className="breadcrumbs"><Link href="/properties">All properties</Link> / {p.area}</div><Gallery photos={p.photos}/><div className="detail-grid"><div><div className="detail-tags"><span>{p.type}</span><span>{p.listingType}</span><span>{status}</span></div><h1>{p.title}</h1><p className="location"><MapPin size={18}/>{p.area}, Duhok</p><dl className="detail-facts">{[['Bedrooms',p.bedrooms],['Bathrooms',p.bathrooms],['Size',`${p.size} m²`],['Status',status]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h2>About this property</h2><p className="description">{p.description}</p><p className="form-note">Listed {new Intl.DateTimeFormat(site.locale,{dateStyle:'long',timeZone:'Asia/Baghdad'}).format(new Date(p.dateListed))} • Reference {p.id}</p></div><aside className="inquiry-box"><p>{p.listingType}</p><div className="price">{priceLabel(p)}{p.listingType==='For Rent'&&<small> / {site.rentalPeriod}</small>}</div><p>{p.status==='Rented'?'This property has recently been rented. Ask us about similar options.':p.status==='Reserved'?'This property is reserved. Ask our team for the latest availability.':'Interested? Speak directly with our team for details or to arrange a viewing.'}</p><a className="button" href={whatsappLink(`Hello ${site.name}, I’m interested in ${p.title} in ${p.area} (reference ${p.id}). Could you share more details?`)} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>Inquire on WhatsApp</a><a className="button secondary" href={`tel:${site.phone}`}>Call {site.name}</a><p>No account needed. Just a conversation.</p></aside></div></div>}
