import Link from 'next/link';
import {site} from '@/config/site';
import {getProperties} from '@/lib/property-store';
import {featuredProperties} from '@/lib/property';
import {PropertyCard} from '@/components/property-card';

export const dynamic='force-dynamic';

export default async function Home(){
  let failed=false;
  const properties=await getProperties().catch(()=>{failed=true;return []});
  const featured=featuredProperties(properties);
  const areas=[...new Set(properties.map(p=>p.area))].filter(Boolean);
  const neighborhoods=areas.length?areas.slice(0,4):['Malta','Zawa','Dream City','Nishtiman'];
  return <>
    <section className="hero">
      <div className="hero-glow"/><div className="skyline" aria-hidden="true"><svg viewBox="0 0 900 620" role="presentation"><path className="skyline-line" d="M0 560h900M85 560V350h90v210M205 560V230h110v330M350 560V115h145v445M535 560V285h90v275M665 560V180h125v380M820 560V320h80v240"/><path className="skyline-fill" d="M85 560V350h90v210M205 560V230h110v330M350 560V115h145v445M535 560V285h90v275M665 560V180h125v380M820 560V320h80v240"/><path className="house-line" d="M115 350l45-52 45 52v210h-90zM134 560V430h52v130M145 377h30"/></svg></div>
      <div className="shell hero-content"><div className="hero-copy"><p className="kicker">Your property partner in Duhok</p><h1><span>Find the place</span><span>that feels like</span><em>the next chapter.</em></h1><p>A considered collection of apartments, houses and land, guided by local knowledge and honest details.</p><div className="hero-actions"><Link href="/properties" className="button">Explore properties</Link><Link href="/request" className="hero-text-link">Tell us what you need <span>↗</span></Link></div></div><div className="hero-meta"><span><strong>{properties.length||'—'}</strong> Listings</span><span><strong>{areas.length||'—'}</strong> Areas covered</span><span><strong>24h</strong> Fast response</span></div></div>
      <form className="search-dock shell" action="/properties"><div className="search-heading"><span className="search-mark"/><span>Begin your search</span></div><label>Looking to<select name="listingType" defaultValue=""><option value="">Rent or buy</option><option value="For Rent">Rent</option><option value="For Sale">Buy</option></select></label><label>Property type<select name="type" defaultValue=""><option value="">Any type</option><option>Apartment</option><option>House</option><option>Land</option></select></label><label>Area<input name="area" placeholder="Any area"/></label><label>Bedrooms<select name="bedrooms" defaultValue=""><option value="">Any beds</option>{[1,2,3,4].map(n=><option key={n} value={n}>{n}+ beds</option>)}</select></label><label>Budget<select name="maxPrice" defaultValue=""><option value="">Any budget</option><option value="50000">Up to $50k</option><option value="100000">Up to $100k</option><option value="250000">Up to $250k</option></select></label><button className="button" type="submit">Search <span>↗</span></button></form>
      <div className="scroll-cue"><span/> Scroll to explore</div>
    </section>
    <section className="category-section shell"><div className="section-heading"><div><p className="kicker">The Avro Sky collection</p><h2>Spaces with a point of view.</h2></div><span className="section-index">01 / 04</span></div><div className="category-grid">{['Apartments','Houses','Lands'].map((category,index)=><Link className="category-tile" key={category} href={`/properties?type=${category==='Lands'?'Land':category.slice(0,-1)}`}><span className="tile-number">0{index+1}</span><span className="tile-icon">{index===0?'▦':index===1?'⌂':'△'}</span><h3>{category}</h3><span className="tile-link">Explore collection ↗</span></Link>)}</div></section>
    <section className="shell section featured-section"><div className="section-heading"><div><p className="kicker">Curated for you</p><h2>{properties.some(p=>p.featured)?'Selected properties':'New to the market'}</h2></div><Link className="text-link" href="/properties">View all properties ↗</Link></div>{failed?<div className="empty-state"><h3>Listings are temporarily unavailable</h3><p>Please check back shortly, or tell us what you are looking for.</p><Link href="/request" className="text-link">Request a property</Link></div>:featured.length?<div className="property-grid">{featured.map(p=><PropertyCard key={p.id} property={p}/>)}</div>:<div className="empty-state">New properties are on the way. Tell us what you need and we’ll help you look.</div>}</section>
    <section className="why-section"><div className="shell"><div className="section-heading"><div><p className="kicker">Why {site.name}</p><h2>Clarity is a luxury.</h2></div></div><div className="why-grid">{[['01','Local perspective','A grounded understanding of Duhok’s neighborhoods, values and opportunities.'],['02','Verified details','Listings presented with the information you need to move with confidence.'],['03','A faster response','Direct conversations, quick answers and a team that keeps things moving.'],['04','No hidden turns','Straightforward guidance from the first question to the final key.']].map(([number,title,text])=><div className="why-item" key={number}><span>{number}</span><i/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="steps-section shell"><div className="section-heading"><div><p className="kicker">A clearer way forward</p><h2>From first thought<br/>to front door.</h2></div></div><div className="steps-grid">{[['01','Tell us what you need','Share your ideal area, budget and the details that matter.'],['02','We find the fit','We search our listings and local network for the right options.'],['03','Make it yours','See the space, ask every question, and take your next step.']].map(([number,title,text])=><div className="step" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="areas-section"><div className="shell"><div className="section-heading"><div><p className="kicker">Know the neighborhood</p><h2>Explore Duhok.</h2></div><span className="section-note">{areas.length||0} areas in our network</span></div><div className="area-grid">{neighborhoods.map((area,index)=><Link href={`/properties?area=${encodeURIComponent(area)}`} className="area-card" key={area}><span>0{index+1}</span><strong>{area}</strong><i>↗</i></Link>)}</div></div></section>
    <section className="request-band"><div className="shell request-band-inner"><div><p className="kicker">Your search can be personal</p><h2>Can’t find what<br/>you want?</h2><p>Tell us what you need and we’ll find the right place for you.</p></div><Link href="/request" className="button light">Find me a property <span>↗</span></Link></div></section>
  </>;
}
