'use client';

import {useActionState,useState} from 'react';
import type {Property} from '@/lib/property';
import {propertyTypes} from '@/lib/property';
import {create,remove,update,type ActionState} from '@/app/admin/actions';

const initial:ActionState={};
function Submit({children}:{children:string}){return <button className="button" type="submit">{children}</button>}
function PropertyForm({property,onClose}:{property?:Property;onClose?:()=>void}){
 const action=property?update:create;const [state,formAction,pending]=useActionState(action,initial);const listedDate=property?.dateListed.slice(0,10)||new Date().toISOString().slice(0,10);
 return <form action={formAction} className="admin-form">{property&&<input type="hidden" name="id" value={property.id}/>}<label className="field full">Title<input name="title" defaultValue={property?.title} required/></label><label className="field">Type<select name="type" defaultValue={property?.type||'Apartment'}>{propertyTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Listing type<select name="listingType" defaultValue={property?.listingType||'For Sale'}><option>For Sale</option><option>For Rent</option></select></label><label className="field">Price (USD)<input name="price" type="number" min="0" step="1" defaultValue={property?.price} required/></label><label className="field">Area<input name="area" defaultValue={property?.area} required/></label><label className="field">Bedrooms<input name="bedrooms" type="number" min="0" step="1" defaultValue={property?.bedrooms??0} required/></label><label className="field">Bathrooms<input name="bathrooms" type="number" min="0" step="1" defaultValue={property?.bathrooms??0} required/></label><label className="field">Size (m²)<input name="size" type="number" min="0" step="1" defaultValue={property?.size??0} required/></label><label className="field">Status<select name="status" defaultValue={property?.status||'Available'}><option>Available</option><option>Reserved</option><option>Rented</option></select></label><label className="field">Date listed<input name="dateListed" type="date" defaultValue={listedDate} required/></label><label className="field full">Description<textarea name="description" rows={4} defaultValue={property?.description} required/></label><label className="field full">Photo URLs (one per line)<textarea name="photos" rows={4} defaultValue={property?.photos.map(p=>p.url).join('\n')} placeholder="https://example.com/photo.jpg"/></label><label className="admin-checkbox full"><input name="featured" type="checkbox" defaultChecked={property?.featured}/> Show in featured listings</label>{state.error&&<p className="error-message">{state.error}</p>}<div className="admin-actions">{onClose&&<button type="button" className="button secondary" onClick={onClose}>Cancel</button>}<Submit>{pending?'Saving…':property?'Save changes':'Add property'}</Submit></div></form>
}
function DeleteButton({id}:{id:string}){const [state,action,pending]=useActionState(remove,initial);return <form action={action} onSubmit={e=>{if(!confirm('Permanently delete this property?'))e.preventDefault()}}><input type="hidden" name="id" value={id}/><button className="admin-delete" type="submit" disabled={pending}>{pending?'Deleting…':'Delete'}</button>{state.error&&<p className="admin-inline-error">{state.error}</p>}</form>}
export function AdminDashboard({properties}:{properties:Property[]}){const [editing,setEditing]=useState<Property>();return <><section className="admin-panel"><div className="admin-section-heading"><div><p className="kicker">New listing</p><h2>Add a property</h2></div></div><PropertyForm/></section><section className="admin-panel"><div className="admin-section-heading"><div><p className="kicker">Inventory</p><h2>All properties</h2></div><span>{properties.length} listings</span></div>{properties.length?<div className="admin-list">{properties.map(p=><article className="admin-row" key={p.id}><div><strong>{p.title}</strong><span>{p.type} · {p.area} · ${p.price.toLocaleString()} · {p.status}</span></div><div className="admin-row-actions"><button className="admin-edit" onClick={()=>setEditing(p)}>Edit</button><DeleteButton id={p.id}/></div></article>)}</div>:<p>No listings yet.</p>}</section>{editing&&<div className="admin-modal" role="dialog" aria-modal="true" aria-label={`Edit ${editing.title}`}><div className="admin-modal-card"><div className="admin-section-heading"><h2>Edit property</h2><button className="admin-close" onClick={()=>setEditing(undefined)} aria-label="Close">×</button></div><PropertyForm property={editing} onClose={()=>setEditing(undefined)}/></div></div>}</>}
