'use client';
import {useState} from 'react';
import {MessageCircle} from 'lucide-react';
import {site,whatsappLink} from '@/config/site';
import {leadSchema,leadSummary,type Lead} from '@/lib/lead';
const initial={propertyType:'Apartment',area:'',bedrooms:'',budget:'',intent:'Rent',timeline:'ASAP',name:'',phone:'',message:'',website:''};
export function RequestForm(){const [form,setForm]=useState(initial);const [error,setError]=useState('');const [pending,setPending]=useState(false);const [done,setDone]=useState<Lead|null>(null);function change(key:keyof typeof initial,value:string){setForm(old=>({...old,[key]:value}));}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const parsed=leadSchema.safeParse(form);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setPending(true);try{const response=await fetch('/api/property-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const data=await response.json() as {ok?:boolean,error?:string};if(!response.ok||!data.ok)throw new Error(data.error||'Unable to send your request.');setDone(parsed.data);}catch(e){setError(e instanceof Error?e.message:'Unable to send your request.');}finally{setPending(false);}}
 if(done)return <section className="success-panel" aria-live="polite"><MessageCircle size={34} color={site.primaryColor}/><h2>Thanks, {done.name}.</h2><p>Your request has been sent to {site.name}. Continue the conversation on WhatsApp if you’d like a faster response.</p><a className="button" target="_blank" rel="noopener noreferrer" href={whatsappLink(leadSummary(done))}>Continue on WhatsApp</a></section>;
 return <form className="lead-form" onSubmit={submit} noValidate>{error&&<div className="error-message" role="alert">{error}</div>}<label className="field">Property Type<select value={form.propertyType} onChange={e=>change('propertyType',e.target.value)}>{['Apartment','House','Villa','Land','Office'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Preferred Area<input required value={form.area} onChange={e=>change('area',e.target.value)} placeholder="e.g. Malta or Zawa"/></label><label className="field">Bedrooms<input required type="number" min="0" max="20" value={form.bedrooms} onChange={e=>change('bedrooms',e.target.value)} placeholder="Number of bedrooms"/></label><label className="field">Budget (USD)<input required type="number" min="1" value={form.budget} onChange={e=>change('budget',e.target.value)} placeholder="Your maximum budget"/></label><fieldset className="full"><legend>What are you looking to do?</legend><div className="toggle"><label><input type="radio" name="intent" checked={form.intent==='Rent'} onChange={()=>change('intent','Rent')}/>Rent</label><label><input type="radio" name="intent" checked={form.intent==='Buy'} onChange={()=>change('intent','Buy')}/>Buy</label></div></fieldset><label className="field full">Timeline<select value={form.timeline} onChange={e=>change('timeline',e.target.value)}><option>ASAP</option><option>Within a month</option><option>Just looking</option></select></label><label className="field">Your Name<input required autoComplete="name" value={form.name} onChange={e=>change('name',e.target.value)} placeholder="Full name"/></label><label className="field">Phone / WhatsApp<input required autoComplete="tel" value={form.phone} onChange={e=>change('phone',e.target.value)} placeholder="+964 ..."/></label><label className="field full">Anything else? <span style={{fontWeight:400}}>(optional)</span><textarea value={form.message} onChange={e=>change('message',e.target.value)} placeholder="Tell us what would make this property right for you."/></label><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>change('website',e.target.value)}/></label><p className="form-note full">By sending this form, you ask {site.name} to contact you about your property search.</p><button className="button full" disabled={pending}>{pending?'Sending request…':'Send my request'}</button></form>}
