import 'server-only';
import {createHash,randomBytes,scrypt as scryptCallback,timingSafeEqual} from 'crypto';
import {promisify} from 'util';
import {neon} from '@neondatabase/serverless';
import {companyId,ensurePropertySchema} from './property-store';

const scrypt=promisify(scryptCallback);
export type StaffRole='Admin'|'Agent';
export type Staff={id:string;companyId:string;name:string;email:string;role:StaffRole;active:boolean};
function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error('The company database is not configured.');return neon(url);}
export async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const derived=await scrypt(password,salt,64) as Buffer;return `${salt}:${derived.toString('hex')}`;}
export async function passwordMatches(password:string,stored:string){const [salt,hash]=stored.split(':');if(!salt||!hash)return false;const derived=await scrypt(password,salt,64) as Buffer;const expected=Buffer.from(hash,'hex');return expected.length===derived.length&&timingSafeEqual(expected,derived);}
export async function ensureAdminSchema(){await ensurePropertySchema();const sql=db();await sql`CREATE TABLE IF NOT EXISTS staff (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),name TEXT NOT NULL,email TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK (role IN ('Admin','Agent')),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,email))`;await sql`CREATE TABLE IF NOT EXISTS clients (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),name TEXT NOT NULL,phone TEXT,whatsapp TEXT,email TEXT,address TEXT,notes TEXT,client_type TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS rentals (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),property_id TEXT NOT NULL REFERENCES properties(id),tenant_client_id TEXT NOT NULL REFERENCES clients(id),monthly_rent NUMERIC NOT NULL CHECK (monthly_rent >= 0),lease_start DATE NOT NULL,lease_end DATE NOT NULL,due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 28),deposit NUMERIC NOT NULL DEFAULT 0,payment_method TEXT,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),rental_id TEXT NOT NULL REFERENCES rentals(id),due_date DATE NOT NULL,amount_due NUMERIC NOT NULL CHECK (amount_due >= 0),amount_paid NUMERIC NOT NULL DEFAULT 0,paid_at TIMESTAMPTZ,status TEXT NOT NULL CHECK (status IN ('Paid','Due Soon','Overdue','Partially Paid')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(rental_id,due_date))`;await sql`CREATE TABLE IF NOT EXISTS message_templates (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),name TEXT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,name))`;await sql`CREATE TABLE IF NOT EXISTS sales (id TEXT PRIMARY KEY,company_id TEXT NOT NULL REFERENCES companies(id),property_id TEXT NOT NULL REFERENCES properties(id),buyer_client_id TEXT REFERENCES clients(id),agent_id TEXT REFERENCES staff(id),sale_type TEXT NOT NULL CHECK (sale_type IN ('Company Owned','Client Listed')),purchase_amount NUMERIC NOT NULL DEFAULT 0,sale_amount NUMERIC NOT NULL,expenses NUMERIC NOT NULL DEFAULT 0,commission_amount NUMERIC NOT NULL DEFAULT 0,sold_at DATE NOT NULL,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;}
export async function bootstrapAdmin(){await ensureAdminSchema();const sql=db();const existing=await sql`SELECT id FROM staff WHERE company_id=${companyId} LIMIT 1`;if(existing.length)return;const email=(process.env.COMPANY_EMAIL||'admin@avrosky.local').replace(/^['"]|['"]$/g,'').trim().toLowerCase();const password=process.env.ADMIN_PASSWORD;if(!password)throw new Error('ADMIN_PASSWORD is required to create the first admin account.');await sql`INSERT INTO staff (id,company_id,name,email,password_hash,role) VALUES (${crypto.randomUUID()},${companyId},'Avro Sky Admin',${email},${await hashPassword(password)},'Admin')`;const templates=[['Payment Due Soon','Hi {tenantName}, this is {adminName} from Avro Sky. We hope you are well. Your rent of {rentAmount} for {propertyName} is due on {dueDate}. Please arrange payment within the next five days.'],['Payment Overdue','Hi {tenantName}, this is {adminName} from Avro Sky. Your rent of {rentAmount} for {propertyName} was due on {dueDate}. Please arrange payment as soon as possible.'],['Lease Ending Soon','Hi {tenantName}, this is {adminName} from Avro Sky. Your lease for {propertyName} ends on {dueDate}. Please contact us to discuss renewal.'],['General Follow-up','Hi {tenantName}, this is {adminName} from Avro Sky. We hope you are well. Please contact us if you need any assistance.']];for(const [name,body] of templates)await sql`INSERT INTO message_templates (id,company_id,name,body) VALUES (${crypto.randomUUID()},${companyId},${name},${body}) ON CONFLICT (company_id,name) DO NOTHING`;}
export async function findStaff(email:string){await bootstrapAdmin();const sql=db();const rows=await sql`SELECT id,company_id,name,email,role,active,password_hash FROM staff WHERE company_id=${companyId} AND email=${email.trim().toLowerCase()} LIMIT 1`;return rows[0] as (Staff&{password_hash:string})|undefined;}
