import 'server-only';
import {neon} from '@neondatabase/serverless';
import {site} from '@/config/site';
import {propertyTypes,type Property} from './property';

export const companyId='avro-sky';
type DatabaseRow={id:string;title:string;type:string;listing_type:string;price:number|string;bedrooms:number|string;bathrooms:number|string;size:number|string;area:string;status:string;description:string;photos:unknown;featured:boolean;date_listed:string|Date;updated_at:string|Date;is_public?:boolean;ownership_kind?:string;owner_client_id?:string|null;assigned_agent_id?:string|null};
function database(){const url=process.env.DATABASE_URL;if(!url)throw new Error('The property database is not configured.');return neon(url);}
function photoList(value:unknown,title:string){const photos=Array.isArray(value)?value:typeof value==='string'?JSON.parse(value):[];return Array.isArray(photos)?photos.filter((p):p is {url:string}=>typeof p?.url==='string'&&p.url.startsWith('https://')).map((p,index)=>({url:p.url,alt:`${title} — photograph ${index+1}`})):[];}
function toProperty(row:DatabaseRow):Property{return {id:row.id,title:row.title,type:row.type as Property['type'],listingType:row.listing_type as Property['listingType'],price:Number(row.price),bedrooms:Number(row.bedrooms),bathrooms:Number(row.bathrooms),size:Number(row.size),area:row.area,status:row.status as Property['status'],description:row.description,photos:photoList(row.photos,row.title),featured:row.featured,dateListed:new Date(row.date_listed).toISOString(),isPublic:row.is_public??true,ownershipKind:row.ownership_kind==='Company Owned'?'Company Owned':'Client Listed',ownerClientId:row.owner_client_id,assignedAgentId:row.assigned_agent_id};}

let schemaReady:Promise<void>|undefined;
/** Runs the idempotent DDL once per server instance instead of on every query. */
export function ensurePropertySchema(){return schemaReady??=createPropertySchema().catch(error=>{schemaReady=undefined;throw error;});}
async function createPropertySchema(){const sql=database();await sql`CREATE TABLE IF NOT EXISTS companies (id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`INSERT INTO companies (id,name) VALUES (${companyId},${site.name}) ON CONFLICT (id) DO NOTHING`;await sql`CREATE TABLE IF NOT EXISTS properties (id TEXT PRIMARY KEY,company_id TEXT NOT NULL DEFAULT 'avro-sky',title TEXT NOT NULL,type TEXT NOT NULL,listing_type TEXT NOT NULL,price NUMERIC NOT NULL CHECK (price >= 0),bedrooms INTEGER NOT NULL DEFAULT 0 CHECK (bedrooms >= 0),bathrooms INTEGER NOT NULL DEFAULT 0 CHECK (bathrooms >= 0),size INTEGER NOT NULL DEFAULT 0 CHECK (size >= 0),area TEXT NOT NULL,status TEXT NOT NULL,description TEXT NOT NULL,photos JSONB NOT NULL DEFAULT '[]'::jsonb,featured BOOLEAN NOT NULL DEFAULT FALSE,is_public BOOLEAN NOT NULL DEFAULT TRUE,ownership_kind TEXT NOT NULL DEFAULT 'Client Listed',owner_client_id TEXT,assigned_agent_id TEXT,date_listed TIMESTAMPTZ NOT NULL DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),deleted_at TIMESTAMPTZ)`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS company_id TEXT NOT NULL DEFAULT 'avro-sky'`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT TRUE`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS ownership_kind TEXT NOT NULL DEFAULT 'Client Listed'`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS owner_client_id TEXT`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS assigned_agent_id TEXT`;await sql`ALTER TABLE properties ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ`;await sql`CREATE INDEX IF NOT EXISTS properties_company_status_idx ON properties(company_id,status)`;await sql`CREATE INDEX IF NOT EXISTS properties_company_area_idx ON properties(company_id,area)`;}
export async function getProperties():Promise<Property[]>{await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties WHERE company_id=${companyId} AND deleted_at IS NULL AND status='Available' AND is_public=TRUE ORDER BY date_listed DESC,id ASC`;return (rows as DatabaseRow[]).map(toProperty);}
export async function getAllProperties():Promise<Property[]>{await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties WHERE company_id=${companyId} AND deleted_at IS NULL ORDER BY date_listed DESC,id ASC`;return (rows as DatabaseRow[]).map(toProperty);}
export async function getPublicProperty(id:string){if(!id)return undefined;await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties WHERE company_id=${companyId} AND deleted_at IS NULL AND status='Available' AND is_public=TRUE AND id=${id} LIMIT 1`;return rows[0]?toProperty(rows[0] as DatabaseRow):undefined;}
function numberField(value:FormDataEntryValue|null,label:string){const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error(`${label} must be a zero or positive number.`);return n;}
function fieldsFromForm(form:FormData){const title=String(form.get('title')||'').trim();const area=String(form.get('area')||'').trim();const description=String(form.get('description')||'').trim();const type=String(form.get('type')||'');const listingType=String(form.get('listingType')||'');const status=String(form.get('status')||'');const dateListed=String(form.get('dateListed')||'');const ownershipKind=String(form.get('ownershipKind')||'Client Listed');if(!title||!area||!description)throw new Error('Title, area, and description are required.');if(!/^\d{4}-\d{2}-\d{2}$/.test(dateListed))throw new Error('Date listed must be a valid date.');if(!propertyTypes.includes(type as Property['type'])||!['For Rent','For Sale'].includes(listingType)||!['Available','Reserved','Rented','Sold','Off Market'].includes(status)||!['Company Owned','Client Listed'].includes(ownershipKind))throw new Error('One of the selected options is invalid.');const photoUrls=String(form.get('photos')||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(photoUrls.some(url=>!/^https:\/\//.test(url)))throw new Error('Each photo URL must start with https://');return {title,type,listingType,price:numberField(form.get('price'),'Price'),bedrooms:numberField(form.get('bedrooms'),'Bedrooms'),bathrooms:numberField(form.get('bathrooms'),'Bathrooms'),size:numberField(form.get('size'),'Size'),area,status,description,photos:JSON.stringify(photoUrls.map(url=>({url}))),featured:form.get('featured')==='on',isPublic:form.get('isPublic')==='on',ownershipKind,dateListed};}
export async function createProperty(form:FormData){await ensurePropertySchema();const f=fieldsFromForm(form);const sql=database();await sql`INSERT INTO properties (id,company_id,title,type,listing_type,price,bedrooms,bathrooms,size,area,status,description,photos,featured,is_public,ownership_kind,date_listed) VALUES (${crypto.randomUUID()},${companyId},${f.title},${f.type},${f.listingType},${f.price},${f.bedrooms},${f.bathrooms},${f.size},${f.area},${f.status},${f.description},${f.photos}::jsonb,${f.featured},${f.isPublic},${f.ownershipKind},${f.dateListed})`;}
export async function updateProperty(id:string,form:FormData){if(!id)throw new Error('Invalid property ID.');await ensurePropertySchema();const f=fieldsFromForm(form);const sql=database();await sql`UPDATE properties SET title=${f.title},type=${f.type},listing_type=${f.listingType},price=${f.price},bedrooms=${f.bedrooms},bathrooms=${f.bathrooms},size=${f.size},area=${f.area},status=${f.status},description=${f.description},photos=${f.photos}::jsonb,featured=${f.featured},is_public=${f.isPublic},ownership_kind=${f.ownershipKind},date_listed=${f.dateListed},updated_at=NOW() WHERE company_id=${companyId} AND id=${id}`;}
export async function deleteProperty(id:string){if(!id)throw new Error('Invalid property ID.');await ensurePropertySchema();const sql=database();await sql`UPDATE properties SET deleted_at=NOW(),is_public=FALSE,updated_at=NOW() WHERE company_id=${companyId} AND id=${id} AND deleted_at IS NULL`;}
