import 'server-only';
import {neon} from '@neondatabase/serverless';
import {propertyTypes,type Property} from './property';

type DatabaseRow={id:string;title:string;type:string;listing_type:string;price:number|string;bedrooms:number|string;bathrooms:number|string;size:number|string;area:string;status:string;description:string;photos:unknown;featured:boolean;date_listed:string|Date;updated_at:string|Date};
function database(){const url=process.env.DATABASE_URL;if(!url)throw new Error('The property database is not configured.');return neon(url);}
function photoList(value:unknown,title:string){const photos=Array.isArray(value)?value:typeof value==='string'?JSON.parse(value):[];return Array.isArray(photos)?photos.filter((p):p is {url:string}=>typeof p?.url==='string'&&p.url.startsWith('https://')).map((p,index)=>({url:p.url,alt:`${title} — photograph ${index+1}`})):[];}
function toProperty(row:DatabaseRow):Property{return {id:row.id,title:row.title,type:row.type as Property['type'],listingType:row.listing_type as Property['listingType'],price:Number(row.price),bedrooms:Number(row.bedrooms),bathrooms:Number(row.bathrooms),size:Number(row.size),area:row.area,status:row.status as Property['status'],description:row.description,photos:photoList(row.photos,row.title),featured:row.featured,dateListed:new Date(row.date_listed).toISOString()};}

export async function ensurePropertySchema(){const sql=database();await sql`CREATE TABLE IF NOT EXISTS properties (id TEXT PRIMARY KEY,title TEXT NOT NULL,type TEXT NOT NULL,listing_type TEXT NOT NULL,price NUMERIC NOT NULL CHECK (price >= 0),bedrooms INTEGER NOT NULL DEFAULT 0 CHECK (bedrooms >= 0),bathrooms INTEGER NOT NULL DEFAULT 0 CHECK (bathrooms >= 0),size INTEGER NOT NULL DEFAULT 0 CHECK (size >= 0),area TEXT NOT NULL,status TEXT NOT NULL,description TEXT NOT NULL,photos JSONB NOT NULL DEFAULT '[]'::jsonb,featured BOOLEAN NOT NULL DEFAULT FALSE,date_listed TIMESTAMPTZ NOT NULL DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;}
export async function getProperties():Promise<Property[]>{await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties WHERE status IN ('Available','Reserved') OR (status='Rented' AND updated_at > NOW() - INTERVAL '7 days') ORDER BY date_listed DESC,id ASC`;return (rows as DatabaseRow[]).map(toProperty);}
export async function getAllProperties():Promise<Property[]>{await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties ORDER BY date_listed DESC,id ASC`;return (rows as DatabaseRow[]).map(toProperty);}
export async function getProperty(id:string){if(!id)return undefined;await ensurePropertySchema();const sql=database();const rows=await sql`SELECT * FROM properties WHERE id=${id} LIMIT 1`;return rows[0]?toProperty(rows[0] as DatabaseRow):undefined;}
function numberField(value:FormDataEntryValue|null,label:string){const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error(`${label} must be a zero or positive number.`);return n;}
function fieldsFromForm(form:FormData){const title=String(form.get('title')||'').trim();const area=String(form.get('area')||'').trim();const description=String(form.get('description')||'').trim();const type=String(form.get('type')||'');const listingType=String(form.get('listingType')||'');const status=String(form.get('status')||'');const dateListed=String(form.get('dateListed')||'');if(!title||!area||!description)throw new Error('Title, area, and description are required.');if(!/^\d{4}-\d{2}-\d{2}$/.test(dateListed))throw new Error('Date listed must be a valid date.');if(!propertyTypes.includes(type as Property['type'])||!['For Rent','For Sale'].includes(listingType)||!['Available','Reserved','Rented'].includes(status))throw new Error('One of the selected options is invalid.');const photoUrls=String(form.get('photos')||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(photoUrls.some(url=>!/^https:\/\//.test(url)))throw new Error('Each photo URL must start with https://');return {title,type,listingType,price:numberField(form.get('price'),'Price'),bedrooms:numberField(form.get('bedrooms'),'Bedrooms'),bathrooms:numberField(form.get('bathrooms'),'Bathrooms'),size:numberField(form.get('size'),'Size'),area,status,description,photos:JSON.stringify(photoUrls.map(url=>({url}))),featured:form.get('featured')==='on',dateListed};}
export async function createProperty(form:FormData){await ensurePropertySchema();const f=fieldsFromForm(form);const sql=database();await sql`INSERT INTO properties (id,title,type,listing_type,price,bedrooms,bathrooms,size,area,status,description,photos,featured,date_listed) VALUES (${crypto.randomUUID()},${f.title},${f.type},${f.listingType},${f.price},${f.bedrooms},${f.bathrooms},${f.size},${f.area},${f.status},${f.description},${f.photos}::jsonb,${f.featured},${f.dateListed})`;}
export async function updateProperty(id:string,form:FormData){if(!id)throw new Error('Invalid property ID.');await ensurePropertySchema();const f=fieldsFromForm(form);const sql=database();await sql`UPDATE properties SET title=${f.title},type=${f.type},listing_type=${f.listingType},price=${f.price},bedrooms=${f.bedrooms},bathrooms=${f.bathrooms},size=${f.size},area=${f.area},status=${f.status},description=${f.description},photos=${f.photos}::jsonb,featured=${f.featured},date_listed=${f.dateListed},updated_at=NOW() WHERE id=${id}`;}
export async function deleteProperty(id:string){if(!id)throw new Error('Invalid property ID.');await ensurePropertySchema();const sql=database();await sql`DELETE FROM properties WHERE id=${id}`;}
export async function importProperties(properties:Property[]){await ensurePropertySchema();const sql=database();for(const p of properties){await sql`INSERT INTO properties (id,title,type,listing_type,price,bedrooms,bathrooms,size,area,status,description,photos,featured,date_listed) VALUES (${p.id},${p.title},${p.type},${p.listingType},${p.price},${p.bedrooms},${p.bathrooms},${p.size},${p.area},${p.status},${p.description},${JSON.stringify(p.photos.map(photo=>({url:photo.url})))}::jsonb,${p.featured},${p.dateListed}) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,type=EXCLUDED.type,listing_type=EXCLUDED.listing_type,price=EXCLUDED.price,bedrooms=EXCLUDED.bedrooms,bathrooms=EXCLUDED.bathrooms,size=EXCLUDED.size,area=EXCLUDED.area,status=EXCLUDED.status,description=EXCLUDED.description,photos=EXCLUDED.photos,featured=EXCLUDED.featured,date_listed=EXCLUDED.date_listed`;} }
