import type {Lang} from './config';

/** Interface text for the admin area only. Property, client and financial data is never translated. {site} is replaced with the company name. */
export const adminCookie='avro_admin_lang';

export const adminEn={
  meta:{offers:'Admin offers',basic:'Basic property admin',pro:'Pro management preview'},
  common:{home:'Home',allSystems:'All systems',private:'Private area',signOut:'Sign out',email:'Email',password:'Password',signIn:'Sign in',signingIn:'Signing in…',saving:'Saving…',close:'Close',otherLang:'عربي'},
  header:{home:'Home',properties:'Properties',findMe:'Find me a property',callUs:'Call us',whatsappUs:'WhatsApp us',openNav:'Open navigation',closeNav:'Close navigation',mainNav:'Main navigation'},
  footer:{tagline:'Property. People. Possibility.',explore:'Explore',allProperties:'All properties',requestProperty:'Request a property',talk:'Let’s talk',callUs:'Call us',whatsapp:'WhatsApp'},
  offers:{loginTitle:'{site} admin',loginText:'Sign in to view the two management-system options.',title:'Choose your system',text:'Compare the simple property manager with the full real-estate management system.',offer1:'Offer 01',basicTitle:'Basic property admin',basicText:'Manage property listings, availability, public visibility, descriptions, prices, and photos.',basicLi:['Add, edit, and remove listings','Upload property photos','Publish available listings to the website'],basicOpen:'Open Basic system',offer2:'Offer 02',proTitle:'Pro company management',proText:'A complete operations workspace for properties, clients, rent, payments, sales, and team work.',proLi:['Rental payment reminders and WhatsApp messages','Sales, commissions, expenses, and profit tracking','Client records, staff roles, and company dashboard'],proOpen:'Open Pro preview',proLocked:'Not available on your plan',proLockedText:'The Pro system is not included in your current plan.'},
  basic:{kicker:'Offer 01 · Basic',loginTitle:'Property admin',loginText:'Sign in to manage property listings and photos.',title:'Property admin',text:'A focused listing manager. Changes appear on the public property catalogue immediately.',compare:'Compare offers',viewSite:'View website',
    newListing:'New listing',addProperty:'Add a property',inventory:'Inventory',allProperties:'All properties',listings:'listings',none:'No listings yet.',edit:'Edit',del:'Delete',deleting:'Deleting…',confirmDelete:'Permanently delete this property?',editProperty:'Edit property',editAria:'Edit {title}',
    fTitle:'Title',fType:'Type',fListingType:'Listing type',fPrice:'Price (USD)',fArea:'Area',fBedrooms:'Bedrooms',fBathrooms:'Bathrooms',fSize:'Size (m²)',fStatus:'Status',fOwnership:'Ownership',fDate:'Date listed',fDescription:'Description',fPhotos:'Property photos',fPhotoUrls:'Photo URLs (one per line)',photoUrlsHint:'Upload photos above, or paste an https:// link',uploading:'Uploading photos…',uploadHint:'Upload JPG, PNG, WebP, or AVIF files (up to 15 MB each).',uploadFailed:'Photo upload failed. Please try again.',featured:'Show in featured listings',isPublic:'Show publicly when available',cancel:'Cancel',saveChanges:'Save changes',add:'Add property'},
  pro:{kicker:'Offer 02 · Pro',loginTitle:'Company management',loginText:'Sign in to view the Pro system preview.',title:'Real-estate management',text:'Live company workspace for properties, clients, rentals, payments, sales, and staff.',
    tabs:{'Dashboard':'Dashboard','Properties':'Properties','Clients':'Clients','Rentals':'Rentals','Sales & profit':'Sales & profit','Messages':'Messages','Staff':'Staff'} as Record<string,string>,
    roles:{Admin:'Admin',Agent:'Agent'} as Record<string,string>,
    statuses:{'Paid':'Paid','Due Soon':'Due soon','Overdue':'Overdue','Partially Paid':'Partially paid'} as Record<string,string>,
    propertyStatuses:{'Available':'Available','Reserved':'Reserved','Rented':'Rented','Sold':'Sold','Off Market':'Off market'} as Record<string,string>,
    listingTypes:{'For Sale':'For sale','For Rent':'For rent'} as Record<string,string>,
    saleTypes:{'Company Owned':'Company owned','Client Listed':'Client listed'} as Record<string,string>,
    clientTypes:{Buyer:'Buyer',Tenant:'Tenant',Landlord:'Landlord',Seller:'Seller',Investor:'Investor',Owner:'Owner'} as Record<string,string>,
    kickerMgmt:'Pro management',access:'{role} access',paidRents:'Rent collected this month',paidSub:'Paid against this month’s rent',dueSoon:'Upcoming rent',dueSub:'Due soon — send a reminder',overdueRent:'Overdue rent',overdueSub:'Needs follow-up',netProfit:'Net sales profit',netSub:'After expenses and commission',attention:'Payment attention',overdueMsg:'{amount} is overdue and needs follow-up.',noOverdue:'No overdue payments right now.',dueOn:'Due {date}',leasesEnding:'Leases ending within 30 days',endsIn:'in {days} days',recentActivity:'Recent activity',propsCount:'Properties in the system',clientsCount:'Clients on file',
    propsText:'Add, edit and photograph listings in the Basic property manager.',openManager:'Open property manager',noContact:'No contact details',noResults:'Nothing matches your search.',
    searchProperties:'Search properties…',allStatuses:'All statuses',allTypes:'All types',allListings:'Sale and rent',searchClients:'Search clients…',allClientTypes:'All client types',searchRentals:'Search tenant or property…',searchSales:'Search sales…',allSaleTypes:'All sale types',
    name:'Name',type:'Type',phone:'Phone',whatsapp:'WhatsApp',email:'Email',address:'Address',notes:'Notes',addClient:'Add client',openProfile:'Open profile',clientProfile:'Client profile',clientSince:'client since',leasesLabel:'Active leases',outstanding:'Outstanding rent',purchasesLabel:'Purchases',saveChanges:'Save changes',removeClient:'Remove client',confirmRemoveClient:'Remove this client from your records?',
    property:'Property',tenant:'Tenant',choose:'Choose',monthlyRent:'Monthly rent',deposit:'Deposit',leaseStarts:'Lease starts',leaseEnds:'Lease ends',dueDay:'Due day',payMethod:'Payment method',payMethodPh:'Cash / transfer',createLease:'Create lease',
    tracker:'Payment tracker',tenantProp:'Tenant / property',due:'Due',amount:'Amount',status:'Status',action:'Action',save:'Save',paidInFull:'Paid in full',paidFor:'Paid amount for {name}',leases:'Leases',perMonth:'/month',dueOnDay:'Due on day {day}',ends:'Ends {date}',ended:'Ended',endLease:'End lease',confirmEndLease:'End this lease? No new rent will be tracked for it.',
    sendReminder:'WhatsApp reminder',reminderTitle:'WhatsApp reminder',template:'Template',message:'Message',noWhatsapp:'This client has no WhatsApp or phone number on file.',openWhatsapp:'Open WhatsApp',copy:'Copy message',copied:'Copied',defaultReminder:'Hi {tenantName}, your rent of {rentAmount} for {propertyName} is due on {dueDate}.',
    templateName:'Template name',placeholders:'Available placeholders:',addTemplate:'Add template',confirmDeleteTemplate:'Delete this message template?',
    saleType:'Sale type',buyer:'Buyer',agent:'Agent',notRecorded:'Not recorded',purchase:'Purchase amount',saleAmount:'Sale amount',expenses:'Expenses',commission:'Commission',revenue:'Sales revenue',soldDate:'Sold date',recordSale:'Record sale',netProfitOf:'net profit',sold:'Sold {date}',sale:'Sale',
    role:'Role',passwordL:'Password',newPassword:'New password (optional)',addStaff:'Add staff member',active:'Active',inactive:'Inactive',you:'you'},
};
export type AdminDict=typeof adminEn;

export const adminAr:AdminDict={
  meta:{offers:'عروض الإدارة',basic:'إدارة العقارات الأساسية',pro:'معاينة الإدارة المتقدمة'},
  common:{home:'الرئيسية',allSystems:'جميع الأنظمة',private:'منطقة خاصة',signOut:'تسجيل الخروج',email:'البريد الإلكتروني',password:'كلمة المرور',signIn:'تسجيل الدخول',signingIn:'جارٍ تسجيل الدخول…',saving:'جارٍ الحفظ…',close:'إغلاق',otherLang:'EN'},
  header:{home:'الرئيسية',properties:'العقارات',findMe:'ابحث لي عن عقار',callUs:'اتصل بنا',whatsappUs:'تواصل عبر واتساب',openNav:'فتح القائمة',closeNav:'إغلاق القائمة',mainNav:'القائمة الرئيسية'},
  footer:{tagline:'عقار. ناس. إمكانيات.',explore:'استكشف',allProperties:'جميع العقارات',requestProperty:'اطلب عقاراً',talk:'لنتحدث',callUs:'اتصل بنا',whatsapp:'واتساب'},
  offers:{loginTitle:'إدارة {site}',loginText:'سجّل الدخول لعرض خيارَي نظام الإدارة.',title:'اختر نظامك',text:'قارن بين مدير العقارات البسيط ونظام إدارة العقارات المتكامل.',offer1:'العرض 01',basicTitle:'إدارة العقارات الأساسية',basicText:'أدِر قوائم العقارات والتوفر والظهور للعامة والأوصاف والأسعار والصور.',basicLi:['إضافة القوائم وتعديلها وحذفها','رفع صور العقارات','نشر القوائم المتاحة على الموقع'],basicOpen:'افتح النظام الأساسي',offer2:'العرض 02',proTitle:'إدارة الشركة المتقدمة',proText:'مساحة عمل متكاملة للعقارات والعملاء والإيجارات والدفعات والمبيعات وعمل الفريق.',proLi:['تذكيرات دفع الإيجار ورسائل واتساب','تتبع المبيعات والعمولات والمصاريف والأرباح','سجلات العملاء وأدوار الموظفين ولوحة الشركة'],proOpen:'افتح المعاينة المتقدمة',proLocked:'غير متاح في خطتك',proLockedText:'النظام المتقدم غير مشمول في خطتك الحالية.'},
  basic:{kicker:'العرض 01 · الأساسي',loginTitle:'إدارة العقارات',loginText:'سجّل الدخول لإدارة قوائم العقارات والصور.',title:'إدارة العقارات',text:'مدير قوائم مركّز. تظهر التغييرات في كتالوج العقارات العام فوراً.',compare:'قارن العروض',viewSite:'عرض الموقع',
    newListing:'قائمة جديدة',addProperty:'إضافة عقار',inventory:'المخزون',allProperties:'جميع العقارات',listings:'قائمة',none:'لا توجد قوائم بعد.',edit:'تعديل',del:'حذف',deleting:'جارٍ الحذف…',confirmDelete:'هل تريد حذف هذا العقار نهائياً؟',editProperty:'تعديل العقار',editAria:'تعديل {title}',
    fTitle:'العنوان',fType:'النوع',fListingType:'نوع القائمة',fPrice:'السعر (دولار)',fArea:'المنطقة',fBedrooms:'غرف النوم',fBathrooms:'الحمامات',fSize:'المساحة (م²)',fStatus:'الحالة',fOwnership:'الملكية',fDate:'تاريخ الإدراج',fDescription:'الوصف',fPhotos:'صور العقار',fPhotoUrls:'روابط الصور (رابط في كل سطر)',photoUrlsHint:'ارفع الصور أعلاه، أو الصق رابط https://',uploading:'جارٍ رفع الصور…',uploadHint:'ارفع ملفات JPG أو PNG أو WebP أو AVIF (حتى 15 ميغابايت لكل ملف).',uploadFailed:'فشل رفع الصور. حاول مرة أخرى.',featured:'إظهار ضمن القوائم المميزة',isPublic:'إظهار للعامة عند التوفر',cancel:'إلغاء',saveChanges:'حفظ التغييرات',add:'إضافة عقار'},
  pro:{kicker:'العرض 02 · المتقدم',loginTitle:'إدارة الشركة',loginText:'سجّل الدخول لعرض معاينة النظام المتقدم.',title:'إدارة العقارات',text:'مساحة عمل مباشرة للشركة للعقارات والعملاء والإيجارات والدفعات والمبيعات والموظفين.',
    tabs:{'Dashboard':'لوحة التحكم','Properties':'العقارات','Clients':'العملاء','Rentals':'الإيجارات','Sales & profit':'المبيعات والأرباح','Messages':'الرسائل','Staff':'الموظفون'},
    roles:{Admin:'مدير',Agent:'وسيط'},
    statuses:{'Paid':'مدفوع','Due Soon':'مستحق قريباً','Overdue':'متأخر','Partially Paid':'مدفوع جزئياً'},
    propertyStatuses:{'Available':'متاح','Reserved':'محجوز','Rented':'مؤجر','Sold':'مباع','Off Market':'خارج السوق'},
    listingTypes:{'For Sale':'للبيع','For Rent':'للإيجار'},
    saleTypes:{'Company Owned':'ملك الشركة','Client Listed':'مدرج من عميل'},
    clientTypes:{Buyer:'مشترٍ',Tenant:'مستأجر',Landlord:'مؤجّر',Seller:'بائع',Investor:'مستثمر',Owner:'مالك'},
    kickerMgmt:'الإدارة المتقدمة',access:'صلاحية {role}',paidRents:'الإيجارات المحصّلة هذا الشهر',paidSub:'المدفوع من إيجار هذا الشهر',dueSoon:'إيجارات قادمة',dueSub:'مستحقة قريباً — أرسل تذكيراً',overdueRent:'إيجارات متأخرة',overdueSub:'تحتاج إلى متابعة',netProfit:'صافي أرباح المبيعات',netSub:'بعد المصاريف والعمولة',attention:'تنبيه الدفعات',overdueMsg:'{amount} متأخرة وتحتاج إلى متابعة.',noOverdue:'لا توجد دفعات متأخرة حالياً.',dueOn:'الاستحقاق {date}',leasesEnding:'عقود تنتهي خلال 30 يوماً',endsIn:'بعد {days} يوم',recentActivity:'النشاط الأخير',propsCount:'العقارات في النظام',clientsCount:'العملاء المسجّلون',
    propsText:'أضف القوائم وعدّلها وارفع صورها من مدير العقارات الأساسي.',openManager:'افتح مدير العقارات',noContact:'لا توجد بيانات تواصل',noResults:'لا توجد نتائج مطابقة لبحثك.',
    searchProperties:'ابحث في العقارات…',allStatuses:'كل الحالات',allTypes:'كل الأنواع',allListings:'بيع وإيجار',searchClients:'ابحث في العملاء…',allClientTypes:'كل أنواع العملاء',searchRentals:'ابحث عن مستأجر أو عقار…',searchSales:'ابحث في المبيعات…',allSaleTypes:'كل أنواع البيع',
    name:'الاسم',type:'النوع',phone:'الهاتف',whatsapp:'واتساب',email:'البريد الإلكتروني',address:'العنوان',notes:'ملاحظات',addClient:'إضافة عميل',openProfile:'فتح الملف',clientProfile:'ملف العميل',clientSince:'عميل منذ',leasesLabel:'العقود الجارية',outstanding:'إيجار مستحق',purchasesLabel:'المشتريات',saveChanges:'حفظ التغييرات',removeClient:'إزالة العميل',confirmRemoveClient:'هل تريد إزالة هذا العميل من سجلاتك؟',
    property:'العقار',tenant:'المستأجر',choose:'اختر',monthlyRent:'الإيجار الشهري',deposit:'التأمين',leaseStarts:'بداية العقد',leaseEnds:'نهاية العقد',dueDay:'يوم الاستحقاق',payMethod:'طريقة الدفع',payMethodPh:'نقداً / تحويل',createLease:'إنشاء عقد',
    tracker:'متابعة الدفعات',tenantProp:'المستأجر / العقار',due:'الاستحقاق',amount:'المبلغ',status:'الحالة',action:'الإجراء',save:'حفظ',paidInFull:'مدفوع بالكامل',paidFor:'المبلغ المدفوع من {name}',leases:'العقود',perMonth:'/شهر',dueOnDay:'الاستحقاق في اليوم {day}',ends:'ينتهي {date}',ended:'منتهٍ',endLease:'إنهاء العقد',confirmEndLease:'هل تريد إنهاء هذا العقد؟ لن تُتابَع إيجارات جديدة له.',
    sendReminder:'تذكير واتساب',reminderTitle:'تذكير واتساب',template:'القالب',message:'الرسالة',noWhatsapp:'لا يوجد رقم واتساب أو هاتف لهذا العميل.',openWhatsapp:'افتح واتساب',copy:'نسخ الرسالة',copied:'تم النسخ',defaultReminder:'Hi {tenantName}, your rent of {rentAmount} for {propertyName} is due on {dueDate}.',
    templateName:'اسم القالب',placeholders:'الحقول المتاحة:',addTemplate:'إضافة قالب',confirmDeleteTemplate:'هل تريد حذف قالب الرسالة هذا؟',
    saleType:'نوع البيع',buyer:'المشتري',agent:'الوسيط',notRecorded:'غير مسجّل',purchase:'مبلغ الشراء',saleAmount:'مبلغ البيع',expenses:'المصاريف',commission:'العمولة',revenue:'إيرادات المبيعات',soldDate:'تاريخ البيع',recordSale:'تسجيل البيع',netProfitOf:'صافي الربح',sold:'بيع في {date}',sale:'البيع',
    role:'الدور',passwordL:'كلمة المرور',newPassword:'كلمة مرور جديدة (اختياري)',addStaff:'إضافة موظف',active:'نشط',inactive:'غير نشط',you:'أنت'},
};
export const adminDictFor=(lang:Lang):AdminDict=>lang==='ar'?adminAr:adminEn;
